### ISSUE TITLE
Should handle SSR properly

### ISSUE THREAD

**Issue by lucifer1004** [googlemap-react/googlemap-react#1]
**Describe the bug** A clear and concise description of what the bug is.

When using with SSR, there will be a warning

```txt
Warning: Expected server HTML to contain a matching <div> in <div>.
```

**To Reproduce** Steps to reproduce the behavior:

1. Run the example next.js project.
2. Go to `localhost:3000/raw`, which uses map components directly.
3. See the warning in browser's console.

**Expected behavior** A clear and concise description of what you expected to
happen.

Should handle SSR properly.

**Comment by lucifer1004** [comment]
#1

**Comment by isBatak** [comment]
it's probably because of this line https://github.com/googlemap-react/googlemap-react/blob/dd67f37631fc2b4fd828cf0fb21c7812df170051/packages/lib/src/components/MapBox.tsx#L122.
On server side `document` is undefined and it renders `null`, but on the client in hydration phase react will render `div` and there will be a missmatch between real DOM and vDOM. Also, in that case react will stop the hydration and recalculate whole DOM again, which is not so good for performance.

**Comment by lucifer1004** [comment]
Thanks, @isBatak , I'll try it.

**Comment by isBatak** [comment]
`mapItemId` could also be a problem, because of `uuid()`. 
Maybe it's enough to provide `id` through props and use `map-${uuid()}` as a fallback.
A better solution would be to use 
```
const mapElementRef = useRef<HTMLDivElement>(null);
...
<div ref={mapElementRef} style={style} className={className} />
``` 
and then instead of `document.getElementById(mapItemId)` just pass `mapElementRef.current`.

**Comment by isBatak** [comment]
Other components like `<CustomControl>` has similar issues with hydration.
I suppose because of `ReactDOM.createPortal` which is not supported on SSR :(
