### ISSUE TITLE
Seems to be caching event handlers

### ISSUE THREAD

**Issue by myleftshoe** [googlemap-react/googlemap-react#3]
I tried this with onClick and onMouseOver on Marker and InfoWindow with same results. The event handlers seem to be retaining state from initial render. Simple example as demo:

Increment the counter using the button then click the "console.log it!" button - it will console.log the current value. Clicking the marker will log a stale value.

```
import React, { useState } from 'react';
import './App.css';
import { GoogleMapProvider, MapBox, Marker } from '@googlemap-react/core'

function App() {
  let [value, setValue] = useState(0);
  return <>
    <GoogleMapProvider>
      <MapBox
        apiKey="YOUR_API_KEY"
        opts={{
          center: { lat: 39, lng: 116 },
          zoom: 11,
        }}
        style={{
          height: '20vh',
          width: '20vw',
        }}
      />
      <Marker
        id="marker"
        opts={{
          draggable: true,
          label: 'hello',
          position: { lat: 39, lng: 116 },
        }}
        onClick={() => console.log('marker', value)}
      />
    </GoogleMapProvider>
    <button onClick={() => setValue(++value)}>+</button>
    <span>{value}</span>
    <p />
    <button onClick={() => console.log('div', value)}>console.log it!</button>
  </>
}

export default App;

```

**Comment by lucifer1004** [comment]
The problem is that when the event listener is registered, the value of `value` is fixed. Since currently the event listener will not be re-registered untill the component is unmounted and mounted again, the output of `console.log` will be stale.

The fix is kinda easy, that is to include `events` as a key variable in the `useGoogleListener` hook. However, this will cause this hook to be called on every rerender, because `events` is an array and will be considered to be different.

A simple solution in your case, however, is to use side effect of the state setter, like:

```javascript
onClick={() => setValue(value => {
  console.log('marker', value)
  return value
})}
```

Wish this will help you.

**Comment by lucifer1004** [comment]
@myleftshoe I released an alpha version `0.1.1-alpha.0`, you can check that.

Currently, I cannot estimate how much this change will affect performance.

**Comment by myleftshoe** [comment]
@lucifer1004 Thankyou again, the alpha works.

**Comment by lucifer1004** [comment]
@all-contributors please add @myleftshoe for bug, idea
